---
AWSTemplateFormatVersion: '2010-09-09'
Description: Role to be assumed by CodePipeline service cross account
Parameters:
  S3Bucket:
    Description: S3 Bucket in the DevOps Account, which holds the artifacts
    Type: String
  DevOpsAccount:
    Description: AWS DevOps AccountNumber
    Type: Number
  CMKARN:
    Description: ARN of the KMS CMK creates in Tools account
    Type: String
Resources:
  CFRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: devopsAccountCodePipelineCFRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref DevOpsAccount
            Action:
              - sts:AssumeRole
      Path: /
  CFPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: devopsAccountCodePipelineCloudFormationPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:ListChangeSets
              - cloudformation:DescribeChangeSet
              - cloudformation:DeleteChangeSet
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}/*
              - !Sub arn:aws:s3:::${S3Bucket}
          -
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:*"
          -
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:Encrypt
            Resource:
              - !Ref CMKARN
      Roles:
        -
          !Ref CFRole
  CFDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformationdeployer-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  CFDeployerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cloudformationdeployer-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: cf
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:ListChangeSets
              - cloudformation:DescribeChangeSet
              - cloudformation:DeleteChangeSet
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:*"
          - Sid: s3
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
              - !Sub "arn:aws:s3:::${S3Bucket}"
          - Sid: iam
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:getRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRole
              - iam:PassRole
              - iam:CreateServiceLinkedRole
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
          - Sid: ssm
            Effect: Allow
            Action:
              - ssm:GetParameters
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
          - Sid: sqs
            Effect: Allow
            Action:
              - sqs:*
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"
          - Sid: cognito
            Effect: Allow
            Action:
              - cognito-idp:*
              - cognito-identity:*
            Resource:
              - "*"
          - Sid: acm
            Effect: Allow
            Action:
              - acm:*
            Resource:
              - "*"
          - Sid: route53
            Effect: Allow
            Action:
              - route53:*
              - s3:*
              - cloudfront:*
            Resource:
              - "*"
          - Sid: dynamodb
            Effect: Allow
            Action:
              - dynamodb:*
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:*"
              - !Sub "arn:aws:dynamodb::${AWS::AccountId}:global-table/*"
          - Sid: lambda
            Effect: Allow
            Action:
              - lambda:CreateEventSourceMapping
              - lambda:CreateFunction
              - lambda:DeleteEventSourceMapping
              - lambda:DeleteFunction
              - lambda:GetEventSourceMapping
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:UpdateFunctionConfiguration
              - lambda:UpdateFunctionCode
            Resource:
              - "*"
          - Sid: apigw
            Effect: Allow
            Action:
              - apigateway:POST
              - apigateway:DELETE
              - apigateway:PATCH
              - apigateway:GET
            Resource:
              - !Sub "arn:aws:apigateway:${AWS::Region}::/*"
      Roles:
        -
          !Ref CFDeployerRole
